spring.application.name=easykart
spring.datasource.url=jdbc:mysql://localhost:3306/easykart
spring.datasource.username=root
spring.datasource.password=Sk@mysql01
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true